name: Use Secret Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as necessary for your project

    - name: Run script using OPENAPI_KEY
      env:                     # Set environment variables
        OPENAPI_KEY: ${{ secrets.OPENAPI_KEY }}  # Access the secret
      run: |
        python app.py  # Replace with your script name that uses the OPENAPI_KEY
